### ISSUE TITLE
pip install into virtualenv does not work correctly

### ISSUE THREAD

**Issue by praseodym** [zardus/mulpyplexer#4]
When I try to `pip install mulpyplexer`, the `mulpyplexer.py` file does not end up in my virtualenv. Changing the `setup.py` file to read `py_modules=['mulpyplexer']` and then installing fixes the problem.

**Comment by praseodym** [comment]
Cheers!

**Comment by zardus** [comment]
:-)

Thanks for letting me know about the issue! I always install with `pip install -e`, so I actually hadn't noticed.
